version: '3.8'

services:
  # Laravel PHP-FPM service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moodle_api_app
    restart: unless-stopped
    volumes:
      - .:/var/www/html # Mount the current directory (your Laravel project) into the container
    ports:
      - "9000:9000" # Expose PHP-FPM port (not directly accessed, but good for debugging)
    environment:
      # Pass environment variables to the PHP-FPM container
      # These will be used by Laravel's env() helper
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MOODLE_BASE_URL: ${MOODLE_BASE_URL}
      MOODLE_MOBILE_SERVICE_SHORTNAME: ${MOODLE_MOBILE_SERVICE_SHORTNAME}
      APP_KEY: ${APP_KEY} # Laravel application key
      APP_DEBUG: ${APP_DEBUG} # Laravel debug mode
    depends_on:
      - db # Ensure database starts before the app

  # Nginx web server
  nginx:
    image: nginx:stable-alpine
    container_name: moodle_api_nginx
    restart: unless-stopped
    ports:
      - "8000:80" # Map host port 8000 to container port 80
    volumes:
      - .:/var/www/html # Mount the Laravel project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Custom Nginx configuration
    depends_on:
      - app # Ensure app (PHP-FPM) starts before Nginx

  # MySQL database
  db:
    image: mysql:8.0 # Using MySQL 8.0
    container_name: moodle_api_db
    restart: unless-stopped
    environment:
      # Database credentials (use values from .env)
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} # Root password for initial setup
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql # Persist database data
    ports:
      - "3307:3306" # Map host port 3307 to container port 3306 (optional, for direct access)

# Docker Volumes for data persistence
volumes:
  db_data: # Volume for MySQL data 